### ISSUE TITLE
KTX: Issue with the offset.

### ISSUE THREAD

**Issue by 0Camus0** [floooh/gliml#3]
Hello,

While trying to load a cubemap compressed with pvrtc4 using ktx I run into an exception at function:

mip_data_and_size

I'm doing a ktx loader myself and I found the issue:

The imgSize returns the size of one face, not of the six, so, imgSize  / 6 will return and incorrect size, and later on an offset mismatch with the next size and failing.

The documentation isn't very clear but debugging the ktx on an hex editor I found that the format follows the format:

mipmap 0:
imgSize [face 1 of size imgSize][face 2 of size imgSize][face 3 of size imgSize][face 4 of size imgSize][face 5 of size imgSize][face 6 of size imgSize]
mipmap 1:
imgSize [face 1 of size imgSize][face 2 of size imgSize][face 3 of size imgSize][face 4 of size imgSize][face 5 of size imgSize][face 6 of size imgSize]

etc.

I renamed the extension to png in order to attach it, but it's ktx.

Regards.
Daniel.

![cube](https://cloud.githubusercontent.com/assets/6864841/11045971/5f6df90a-86df-11e5-8268-2448af340990.png)

**Comment by floooh** [comment]
Thanks for the detailed bug report :) Are you blocked by this? It could be a few days until I can take care of it.

**Comment by 0Camus0** [comment]
No problem, I was looking for reference and found the bug in the way.

Regards!
Daniel.

**Comment by floooh** [comment]
Ok got around to fix this, tested on an iPad. The cubemap is fairly lowres thus the artefacts.
![img_0011](https://cloud.githubusercontent.com/assets/1699414/14440510/6aa4b410-0030-11e6-81ca-f2a01240c0a9.PNG)

Thanks again for the detailed report, it was very helpful.
